### ISSUE TITLE
As SBT plugin ...

### ISSUE THREAD

**Issue by alltonp** [reactormonk/scala-elm-types#2]
Hi,

Thank you for this, it's very useful.

Is this still being maintained? It doesn't seem to have beee touched in a while.

Any plans to turn it into a proper SBT plugin? (Or a jar at least), so we don't have to include the source in every project.

Many thanks,
Paulos

**Comment by reactormonk** [comment]
It's released as a [jar](https://search.maven.org/#artifactdetails%7Corg.reactormonk%7Celmtypes_2.12%7C0.3%7Cjar). How should I link it? And it still works for elm 0.18.

**Comment by alltonp** [comment]
Perfect, thank you. 

I just added the following to my sbt libraryDependencies: "org.reactormonk" % "elmtypes_2.12" % "0.3"

I didn't realise it was published. Maybe add something to the readme?
